export type Course = {
  _id: string;
  ocode0: string;
  ocode0_title: string;
  ocode1: string;
  ocode1_title: string;
  KNA: string;
  EKNA: string;
  PROF: string;
  FILE: string;
  HYHG: string;
  POINT: string;
  CUT1: string;
  CUT2: string;
  CUT3: string;
  CUT4: string;
  MAX: string;
  MAXM: string;
  MINM: string;
  AVGM: string;
  CNT: string;
  PART: string;
  TIME: string;
  CLSR: string;
};
